<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\poke-battle-models\poke-battle-models.csproj" />
    <ProjectReference Include="..\poke-battle-infraestructure\poke-battle-infraestructure.csproj" />
    <ProjectReference Include="..\poke-battle-core\poke-battle-core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>poke_battle_services</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
